import styles from "./marquee.module.scss";

export const DoubleMarquee = () => {
  return (
    <div>
      <div className={styles.logos}>
        <div className={styles.logoSlide}>
          <img
            src="/src/components/cssAnimation/marquee/images/accor.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ABN AMRO.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/alchemy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ambrosia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/arianee.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Asset Reality.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/biconomy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/BNY Mellon.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/boomfi.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/bridgesplit.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/cocreate.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Deloitte.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/due.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Dux.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/FIdelity.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/fis.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/hayvn.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/JOIN.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Koshance.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kravata.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kudelski.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nealthy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nilos.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/NIST.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/pimlico.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Pluckmarket.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/safe.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/SOC.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/sphere.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/tokeny.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Vita Wallet.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/walletconnect.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Yolo.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Zodia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/zulu.svg"
            alt="img"
          />
        </div>

        <div className={styles.logoSlide}>
          <img
            src="/src/components/cssAnimation/marquee/images/accor.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ABN AMRO.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/alchemy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ambrosia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/arianee.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Asset Reality.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/biconomy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/BNY Mellon.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/boomfi.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/bridgesplit.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/cocreate.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Deloitte.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/due.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Dux.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/FIdelity.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/fis.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/hayvn.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/JOIN.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Koshance.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kravata.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kudelski.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nealthy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nilos.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/NIST.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/pimlico.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Pluckmarket.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/safe.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/SOC.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/sphere.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/tokeny.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Vita Wallet.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/walletconnect.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Yolo.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Zodia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/zulu.svg"
            alt="img"
          />
        </div>
      </div>

      <div className={styles.logos}>
        <div className={`${styles.logoSlide} ${styles.reverse}`}>
          <img
            src="/src/components/cssAnimation/marquee/images/accor.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ABN AMRO.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/alchemy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ambrosia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/arianee.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Asset Reality.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/biconomy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/BNY Mellon.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/boomfi.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/bridgesplit.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/cocreate.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Deloitte.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/due.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Dux.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/FIdelity.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/fis.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/hayvn.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/JOIN.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Koshance.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kravata.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kudelski.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nealthy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nilos.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/NIST.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/pimlico.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Pluckmarket.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/safe.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/SOC.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/sphere.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/tokeny.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Vita Wallet.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/walletconnect.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Yolo.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Zodia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/zulu.svg"
            alt="img"
          />
        </div>

        <div className={`${styles.logoSlide} ${styles.reverse}`}>
          <img
            src="/src/components/cssAnimation/marquee/images/accor.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ABN AMRO.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/alchemy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/ambrosia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/arianee.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Asset Reality.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/biconomy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/BNY Mellon.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/boomfi.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/bridgesplit.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/cocreate.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Deloitte.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/due.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Dux.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/FIdelity.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/fis.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/hayvn.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/JOIN.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Koshance.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kravata.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/kudelski.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nealthy.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Nilos.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/NIST.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/pimlico.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Pluckmarket.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/safe.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/SOC.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/sphere.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/tokeny.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Vita Wallet.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/walletconnect.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Yolo.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/Zodia.svg"
            alt="img"
          />
          <img
            src="/src/components/cssAnimation/marquee/images/zulu.svg"
            alt="img"
          />
        </div>
      </div>
    </div>
  );
};
